name: unet-semantic-segmentation
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python version
  - python=3.10
  
  # Core Deep Learning Framework (CPU-only for macOS)
  - pytorch>=2.3.0
  - torchvision>=0.18.0
  
  # Computer Vision and Image Processing
  - opencv>=4.10.0
  - pillow>=11.0.0
  
  # Numerical Computing
  - numpy>=1.26.0
  
  # Data Visualization
  - matplotlib>=3.9.0
  - seaborn>=0.13.0
  
  # Machine Learning
  - scikit-learn>=1.6.0
  
  # Configuration
  - pyyaml>=6.0
  
  # System utilities
  - pip
  - pip:
      # Data Augmentation (better from pip for latest features)
      - albumentations>=2.0.0
      
      # Progress and Utilities
      - tqdm>=4.66.0
      
      # Experiment Tracking and Logging
      - tensorboard>=2.13.0
      - wandb>=0.15.0
      
      # Dataset Download and Processing
      - requests>=2.32.0
