# Configuration file for U-Net Semantic Segmentation

# Model Configuration
model:
  name: "unet"
  input_channels: 3
  num_classes: 21  # Pascal VOC classes
  encoder_depth: 5
  decoder_channels: [512, 256, 128, 64, 32]
  dropout: 0.2

# Training Configuration
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 1e-4
  scheduler: "cosine"
  warmup_epochs: 5
  early_stopping_patience: 15
  
# Data Configuration
data:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  image_size: [512, 512]
  num_workers: 4
  augmentation:
    horizontal_flip: 0.5
    vertical_flip: 0.2
    rotation: 15
    brightness_contrast: 0.2
    blur: 0.1

# Paths
paths:
  model_save_dir: "checkpoints"
  log_dir: "logs"
  output_dir: "outputs"
  
# Logging
logging:
  use_tensorboard: true
  use_wandb: false
  log_interval: 10
  save_interval: 5
